version: 0.0
os: linux
files:
  - source:  /
    # ec2 목적지
    destination: /home/ubuntu/build
hook:
  BeforeInstall:
      - location: /home/ubuntu/build/unzip_shell.sh
        timeout: 60
        runas: root